---
# all non secret vars
zfs:
  {
    poolName: DataPool,
    DISK1: "/dev/disk/by-id/scsi-123abc",
    DISK2: "/dev/disk/by-id/scsi-456def",
    DISK3: "/dev/disk/by-id/scsi-789ghi",
    DISK4: "/dev/disk/by-id/scsi-789ghz",
    CACHEDISK: "/dev/disk/by-id/scsi-424242ababab",
    poolName2: VMPool,
    DISK5: "/dev/disk/by-id/ata-VBOX_HARDDISK_VB0560a824-8f3254f9",
  }

usergroups:
  - family
  - admins

users:
  - { name: "mainuser", groups: "family, admins", smbpasswd: "mainuser" }
  - { name: "otheruser", groups: "family", smbpasswd: "otheruser" }
  - { name: "thirduser", groups: "family", smbpasswd: "thirduser" }
  - { name: "userNotInGroups", groups: "", smbpasswd: "userNotInGroups" }

adminuser: mainuser # should be an existing one from above

shared_folders:
  - { name: "Images", path: "/{{zfs.poolName}}/media/images" }
  - { name: "files", path: "/{{zfs.poolName}}/personal/files" }
  - { name: "Shared folder", path: "/{{zfs.poolName}}/personal/all" }
  - { name: "Shared Backup Folder", path: "/{{zfs.poolName}}/backup/all" }

shared_folders_group: family
