---
  - name: "Setting up the home server"
    hosts: ansible
    become: yes
    become_method: sudo

    vars_files:
        - vars/main_vars.yml

    handlers:
    - name: restart smbd
      ansible.builtin.service:
        name: smbd
        state: restarted

    tasks:
    - import_tasks: tasks/setupZFStask.yml
    - import_tasks: tasks/setupUsersTask.yml
    - import_tasks: tasks/setupSambaTask.yml
